### ISSUE TITLE
Unable to create a top level group in self-hosted GitLab

### ISSUE THREAD

**Issue by BillKlineVT** [crossplane-contrib/provider-gitlab#108]
### What happened?

Using the Group Managed Resource, I am unable to create a group at the top level of GitLab (self-hosted 16.4.1) group hierarchy (i.e. with no Parent ID  or Parent ID Reference).  I looked at the API spec and it does not appear that `parentID` is a required field.

Group YAML:
```
apiVersion: groups.gitlab.crossplane.io/v1alpha1
kind: Group
metadata:
  name: root-test
spec:
  forProvider:
    name: "Root Test"
    path: "root-test"
    description: "root group."
    sharedWithGroups:
  providerConfigRef:
    name: gitlab-provider
  # a reference to a Kubernetes secret to which the controller will write the runnersToken
  writeConnectionSecretToRef:
    name: gitlab-group-root
    namespace: crossplane-system
```

Error shown when `kubectl describe` the resource: `cannot resolve references: mg.Spec.ForProvider.ParentID: strconv.Atoi: parsing "": invalid syntax`

I also tried to include `parentID` with `0` as the value.  Using `0` returns a "404 Group not found" type error.

Notes:
* I was able to successfully create a subgroup of an existing group (by providing the parentID integer), so I have confirmed the connection to my GitLab instance is valid.
* I did see a similar bug ticket that was written/closed: https://github.com/crossplane-contrib/provider-gitlab/issues/22, but that was related to the gitlab.com SaaS only.

### How can we reproduce it?

```
cat << EOF > gitlabGroup.yaml
apiVersion: groups.gitlab.crossplane.io/v1alpha1
kind: Group
metadata:
  name: root-test
spec:
  forProvider:
    name: "Root Test"
    path: "root-test"
    description: "root group."
    sharedWithGroups:
  providerConfigRef:
    name: gitlab-provider
  # a reference to a Kubernetes secret to which the controller will write the runnersToken
  writeConnectionSecretToRef:
    name: gitlab-group-root
    namespace: crossplane-system
EOF

kubectl apply -f gitlabGroup.yaml
```

### What environment did it happen in?
Crossplane version: v1.13.2
Crossplane Provider GitLab version: v0.5.0
Cloud provider or hardware configuration: minikube on a local VM
Kubernetes version: 1.27.4
Kubernetes distribution: minikube
OS: Ubuntu

**Comment by agardnerIT** [comment]
Me too. I'm spinning up a demo system, so all I really want to do is create `n` admin users.

That may not be possible though (I'm guessing) so then I want a single group `users` and to add `n` users to that group:

```
---
apiVersion: groups.gitlab.crossplane.io/v1alpha1
kind: Group
metadata:
  name: users
spec:
  forProvider:
    name: "All Users"
    path: "users"
    description: "All users are in this group"
  providerConfigRef:
    name: gitlab-provider
  writeConnectionSecretToRef:
    name: gitlab-group-users
    namespace: crossplane
---
apiVersion: groups.gitlab.crossplane.io/v1alpha1
kind: Member
metadata:
  name: user1
spec:
  forProvider:
    groupIdRef:
      name: users
    userID: 100
    userName: user1
    accessLevel: 50
  providerConfigRef:
    name: gitlab-provider
  writeConnectionSecretToRef:
    name: gitlab-group-user1
    namespace: crossplane
```
