### ISSUE TITLE
Group not found

### ISSUE THREAD

**Issue by agardnerIT** [crossplane-contrib/provider-gitlab#109]
I have manually created a group and even setting this, crossplane doesn't seem to find it.

Using provider v0.5.0 on crossplane v1.4.1

```
apiVersion: groups.gitlab.crossplane.io/v1alpha1
kind: Member
metadata:
  name: user1
spec:
  forProvider:
    groupdId: 5
    groupIdRef:
      name: manualgroup1
    userID: 100
    userName: user1
    accessLevel: 50
  providerConfigRef:
    name: gitlab-provider
  writeConnectionSecretToRef:
    name: gitlab-group-user1
    namespace: crossplane
```

Resulting error:

```
cannot resolve references: spec.forProvider.groupId: cannot get referenced resource: Group.groups.gitlab.crossplane.io "manualgroup1" not found
```

<img width="483" alt="image" src="https://github.com/crossplane-contrib/provider-gitlab/assets/26523841/9affe95a-71a2-4aaf-a7d1-a16932faf895">
