### ISSUE TITLE
Add Files to Project

### ISSUE THREAD

**Issue by henrysachs** [crossplane-contrib/provider-gitlab#111]
### What problem are you facing?

When creating a project I want to add some initial files so that its not empty. So I have some smooth onboarding process. I currently use crossplane and the provider to provision a group (like a tenant) and a corresponding repository where a user would be able to configure the "tenant".

**Comment by janwillies** [comment]
Are you looking for [Gitlab Templates](https://docs.gitlab.com/ee/user/group/custom_project_templates.html)? If so, have you tried some of the existing options, e.g. [useCustomTemplate](https://marketplace.upbound.io/providers/crossplane-contrib/provider-gitlab/v0.5.0/resources/projects.gitlab.crossplane.io/Project/v1alpha1#doc:spec-forProvider-useCustomTemplate)?

**Comment by d3nnxs** [comment]
https://docs.gitlab.com/ee/api/repository_files.html#create-new-file-in-repository

**Comment by gsharma-jiggzy** [comment]
This would be great if a gitlab repository file could be created

**Comment by quanlk2511** [comment]
Great idea +1

**Comment by quanlk2511** [comment]
Hello guys, any chance that we can have this feature?

**Comment by hosseindehghanpoor** [comment]
hey guys
is there any proposed plan to add this feature in this provider?
i did try to extend this feature but no success achieved

**Comment by vtmocanu** [comment]
Has anyone found any workaround for this?

**Comment by hosseindehghanpoor** [comment]
i did wrote custom function for that. its not that complicated.

**Comment by valdemon** [comment]
Hi, @henrysachs until this is implemented - [provider-http](https://github.com/crossplane-contrib/provider-http) helped me with this use case (as a workaround). Here's the example:
```yaml
apiVersion: http.crossplane.io/v1alpha2
kind: Request
metadata:
  name: manage-gitlab-file
spec:
  forProvider:
    waitTimeout: 2m0s
    # Global headers for all operations
    headers:
      Content-Type:
        - application/json
      PRIVATE-TOKEN:
        # SECRET_NAME:SECRET_NAMESPACE:KEY
        - "{{ gitlab-token:crossplane-system:token }}"
    
    payload:
      # Replace 12345 with your Project ID and 'README.md' with your URL-encoded path
      baseUrl: https://gitlab.com/api/v4/projects/12345/repository/files/README.md
      body: |
        {
          "branch": "main",
          "content": "This file is managed by Crossplane via provider-http.  (updated 7)",
          "commit_message": "Rendered by Crossplane"
        }

    mappings:
      # Scenario 1: CREATE (POST)
      - action: CREATE
        method: POST
        url: .payload.baseUrl
        body: |
          {
            "branch": .payload.body.branch,
            "content": .payload.body.content,
            "commit_message": "Create: " + .payload.body.commit_message
          }

      # Scenario 2: OBSERVE (GET)
      # GitLab GET requires a '?ref=branch_name' query parameter
      - action: OBSERVE
        method: GET
        url: .payload.baseUrl + "?ref=" + .payload.body.branch

      # Scenario 3: UPDATE (PUT)
      - action: UPDATE
        method: PUT
        url: .payload.baseUrl
        body: |
          {
            "branch": .payload.body.branch,
            "content": .payload.body.content,
            "commit_message": "Update: " + .payload.body.commit_message
          }

      # Scenario 4: REMOVE (DELETE)
      - action: REMOVE
        method: DELETE
        url: .payload.baseUrl
        body: |
          {
            "branch": .payload.body.branch,
            "commit_message": "Delete: " + .payload.body.commit_message
          }
    
    # Check if the file content in GitLab matches our desired state
    # Note: GitLab returns content in Base64; .content | @base64d decodes it for comparison
    expectedResponseCheck:
      type: CUSTOM
      logic: |
        if (.response.body.content | @base64d) == .payload.body.content
        then true
        else false
        end

    # If the file is missing, GitLab returns 404
    isRemovedCheck:
      type: CUSTOM
      logic: |
        if .response.statusCode == 404
        then true
        else false
        end

  providerConfigRef:
    name: provider-http
```
Next step is to create an XRD out of it.
One can also use the `DisposableRequest` instead when the use case is of "fire and forget" type.
