### ISSUE TITLE
Project managed resource is not working at all

### ISSUE THREAD

**Issue by mariusz-gomse-centra** [crossplane-contrib/provider-gitlab#123]
### What happened?

I created below Managed Resource:
```
apiVersion: projects.gitlab.crossplane.io/v1alpha1
kind: Project
metadata:
  name: "someproject"
spec:
  forProvider:
    description: "an example project"
    path: "someproject"
    namespaceId: 83105993
  providerConfigRef:
    name: provider-gitlab
```

and it is totally not working (no events, no ready/synced status etc., no logs in the provider container)

I also tried to add `writeConnectionSecretToRef:` but also without success - and no error message, nothing there.

When I do the same with group it works like a charm:
```
apiVersion: groups.gitlab.crossplane.io/v1alpha1
kind: Group
metadata:
  name: "some-group"
spec:
  forProvider:
    parentId: 83105993
    path: "some-group"
  providerConfigRef:
    name: provider-gitlab
```

PS: For groups even if I've some problem there I can see it in the events and ready/sync status but for project there is nothing 😢 

### How can we reproduce it?

Described above

### What environment did it happen in?
Crossplane version: 
Crossplane Provider GitLab version:

* Crossplane version: `helm.sh/chart: crossplane-1.15.0`
* Crossplane Provider GitLab version: `image: xpkg.upbound.io/crossplane-contrib/provider-gitlab:v0.6.0`
* Cloud provider or hardware configuration: `kind`
* Kubernetes version (use `kubectl version`): 
```
kubectl version
Client Version: v1.28.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.3
```
