### ISSUE TITLE
Crossplane 1.15 trying to use Management Policies

### ISSUE THREAD

**Issue by jwhitcraft** [crossplane-contrib/provider-gitlab#136]
### What happened?

I'm trying to import a gitlab group so it can be utilized by references

```
apiVersion: groups.gitlab.crossplane.io/v1alpha1
kind: Group
metadata:
  name: zys
  annotations:
    crossplane.io/external-name: 'zys'
spec:
  managementPolicies: ['Observe']
  forProvider:
    path: 'xyz/zys'

```

But it get this status:

```
atProvider: {}
conditions:
  - lastTransitionTime: 2024-04-25T12:20:39Z
    message: "`spec.managementPolicies` is set to a non-default value but the
      feature is not enabled: [Observe]"
    reason: ReconcileError
    status: "False"
    type: Synced
```

I believe that is caused by the Gitlab still using the `EnableAlphaManagementPolicies` instead of the `EnableBetaManagementPolicies` now that it's gone into Beta.

### How can we reproduce it?

Try and import an existing group with the Observe managementPolicy set.

### What environment did it happen in?
Crossplane version:  1.15.2
Crossplane Provider GitLab version: 0.6.1

$ kubectl version
Client Version: v1.30.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.3-eks-adc7111
