### ISSUE TITLE
feature: Gitlab Runner Users 

### ISSUE THREAD

**Issue by Breee** [crossplane-contrib/provider-gitlab#142]
## What and Why? 

- Gitlab 17 will deprecate the traditional runner registration flow,  thus we need to create  gitlab runner users. 
- As an operator of Gitlab i want to be able to create and manage gitlab runners according to the new registration flow, 
- It would be great to have these runners as Crossplane Managed ressources as they can also automatically write the runner-tokens into a secret which can be picked up by gitlab runner operator or so. 
- This would also enable us to easily rotate gitlab runner registration tokens 

## How 
Schema wise, something similar to  https://registry.terraform.io/providers/gitlabhq/gitlab/latest/docs/resources/user_runner  would be perfect 

```
apiVersion: users.gitlab.crossplane.io/v1alpha1
kind: Runner
metadata:
  name: my-runner
spec:
  forProvider:
    runnerType: instance_type
    description: "My fancy instance runner"
    # (etc..)
   providerConfigRef:
    name: gitlab-provider
  writeConnectionSecretToRef:
    name: my-runner-token
    namespace: crossplane-system
```

What do you think?  (I'd be happy to contribute)
