### ISSUE TITLE
clone buildGitStrategy don't work

### ISSUE THREAD

**Issue by julienpaulino** [crossplane-contrib/provider-gitlab#148]
### What happened?
When I set buildGitStrategy to clone, the Git Strategy in CI/CD settings is not changed.

### How can we reproduce it?
With the following manifest
```
apiVersion: projects.gitlab.crossplane.io/v1alpha1
kind: Project
metadata:
  name: test-infra
  annotations:
    crossplane.io/external-name: "540"
spec:
  deletionPolicy: Orphan
  forProvider:
    allowMergeOnSkippedPipeline: false
    approvalsBeforeMerge: 0
    autocloseReferencedIssues: true
    buildsAccessLevel: enabled
    buildGitStrategy: clone
    ciDefaultGitDepth: 20
    ciForwardDeploymentEnabled: true
    containerRegistryEnabled: true
    defaultBranch: main
    description: Test Infra XXXX
    forkingAccessLevel: enabled
    issuesAccessLevel: enabled
    lfsEnabled: true
    mergeMethod: ff
    mergeRequestsAccessLevel: enabled
    mirror: false
    mirrorOverwritesDivergedBranches: false
    mirrorTriggerBuilds: false
    name: Test Infra
    namespaceId: 852
    onlyAllowMergeIfAllDiscussionsAreResolved: false
    onlyAllowMergeIfPipelineSucceeds: false
    onlyMirrorProtectedBranches: false
    packagesEnabled: true
    pagesAccessLevel: private
    path: test-infra
    publicBuilds: true
    removeSourceBranchAfterMerge: true
    repositoryAccessLevel: enabled
    requestAccessEnabled: true
    resolveOutdatedDiffDiscussions: false
    serviceDeskEnabled: false
    sharedRunnersEnabled: true
    snippetsAccessLevel: enabled
    visibility: private
    wikiAccessLevel: enabled
    containerExpirationPolicyAttributes:
      cadence: 1d
      enabled: false
      keepN: 10
      nameRegexDelete: ''
      nameRegexKeep: ''
      olderThan: 90d
  providerConfigRef:
    name: gitlab-provider
```
The project is mark as Ready and is Sync but in gitlab the Git Strategy in CI/CD settings is not change to clone.

### What environment did it happen in?
Crossplane version: 16
Crossplane Provider GitLab version: 0.8.0
Kubernetes: 1.28.9
Kubernetes distribution: AKS
Gitlab: 17.0.1
