### ISSUE TITLE
What is the proper way to observe a Group created outside of crossplane (without knowing the ID)

### ISSUE THREAD

**Issue by patpicos** [crossplane-contrib/provider-gitlab#163]
### What happened?

I would like to observe a group that was pre-created outside of Crossplane. I wish to look it up based on its name or path, or a combination there of. The goal is to avoid users from populating the group id (they are easy to misconfigure).

I have tried a few approaches without success.

### How can we reproduce it?

Attempt that was closest to get an outcome:
```yaml
apiVersion: groups.gitlab.crossplane.io/v1alpha1
kind: Group
metadata:
  name: nk-rdc-charts-dev
  namespace: isv-onboarding-continuous-deployment
spec:
  deletionPolicy: Delete
  forProvider:
    name: nk-rdc-charts-dev
    path: nk-rdc-dev
    parentId: 741
  managementPolicies:
  - Observe
  providerConfigRef:
    name: gitlab-provider-config
```

The logs show that it found the resource (ID 870), but would not update due to mgmt policies..
```
2024-10-21T14:20:46.717Z        DEBUG   provider-gitlab Skipping update due to managementPolicies. Reconciliation succeeded     {"controller": "managed/group", "request": {"name":"nk-rdc-jzsqb-charts-grp"}, "uid": "fb1adeb6-6d19-4078-b430-b93c2c133b19", "version": "1704501", "external-name": "870", "requeue-after": "2024-10-21T14:21:46.717Z"}
```

The example below failed because the external-name is not an integer (i cant put "870" because thats what i wish to lookup!)
```
apiVersion: groups.gitlab.crossplane.io/v1alpha1
kind: Group
metadata:
  annotations:
    crossplane.io/external-name: nk-rdc-charts-dev
  name: test-observe
  namespace: isv-onboarding-continuous-deployment
spec:
  deletionPolicy: Delete
  # forProvider:
  #   name: nk-rdc-charts-dev
  #   path: nk-rdc-dev
  #   parentId: 741
  managementPolicies:
  - Observe
  providerConfigRef:
    name: gitlab-provider-config
```
Then i tried uncommenting the forProvider because they are required...but that did not work because metadata.name took precedence

I am starting to think i need to create myself a lookup table rather than trying to observe it..
### What environment did it happen in?
Crossplane version: v1.16
Crossplane Provider GitLab version: v0.9.0
