### ISSUE TITLE
DeployKey resource fails with apparent type error

### ISSUE THREAD

**Issue by kingdonb** [crossplane-contrib/provider-gitlab#198]
I'm attempting to create a DeployKey in my Group/Project

Following the guide, I've set `projectId` in the `spec.forProvider` - I had to set it to a string, because it's apparently enforced by the openid spec. Annotations are also strings, so the externalName will be a string.

I managed to get it to Ready state once, but I eventually get this error and it fails to sync again:

```
  Warning  CannotUpdateExternalResource   72s                   managed/deploykey.projects.gitlab.crossplane.io  cannot update Gitlab deploy key: invalid ID type (*string)(0xc0013d7580), the ID must be an int or a string
```

Near as I can tell, this is similar to another error that I worked around by setting `crossplane.io/external-name` to a value, even though I was in `Create` mode not `Observe` - the original message was insisting that external-name should be an int, but annotations cannot be ints, so I set it to an int value in string format, which was enough to get past the snakes there.

But evidently something in here didn't like that, and it wouldn't last.

Here is my DeployKey, names and places changed to protect the innocent:

```yaml
---
apiVersion: projects.gitlab.crossplane.io/v1alpha1
kind: DeployKey
metadata:
  name: example-key
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: Merge
    # Bug:
    # crossplane.io/external-name: "1"
    # Bug - the external-name cannot be unset or the resource is never "Synced"
    # It will plow over this value but you have to set it to something initially
spec:
  managementPolicies: ["*"]
  deletionPolicy: Delete
  forProvider:
    # Bug: projectIdRef says "external-name annotation is not an int"
    # projectIdRef:
    #   name: example-project
    # Bug: follow the example instead, report it as a bug later (please)
    projectId: "9876" # Project ID for my test repository
    title: Sandbox cluster Deploy Key (flux-system)
    canPush: false
    keySecretRef:
      namespace: flux-system
      name: flux-system
      key: identity.pub
  providerConfigRef:
    name: gitlab-provider
  # a reference to a Kubernetes secret to which the controller will write the runnersToken
  writeConnectionSecretToRef:
    name: problematic-example-deploy-key
    namespace: crossplane-system
```

Is it possible this feature is undercooked or not being maintained? I'd prefer to think that I'm using it wrong somehow.
