### ISSUE TITLE
Can no longer set project merge request minimum approvals required

### ISSUE THREAD

**Issue by daniel-palmer-gu** [crossplane-contrib/provider-gitlab#206]
### What happened?

With an update to the go-client for GitLab, we [removed some features](https://github.com/crossplane-contrib/provider-gitlab/commit/33b446c89a45375d766d339c2ab2199b472b7d9c) from the Projects XRD as they were deprecated upstream.

In particular, [ApprovalsBeforeMerge](https://github.com/crossplane-contrib/provider-gitlab/commit/33b446c89a45375d766d339c2ab2199b472b7d9c#diff-8c8b44e15b8ba788f378503a00f9ab9ce4f8be3a3ca65caadeadf59e2785ea1bL159) was removed. This is problematic because the non-deprecated version requires creating [project approval rules](https://docs.gitlab.com/api/merge_request_approvals/#create-project-approval-rule) which are not supported by this provider.

Can we please revert this change or add support for project approval rules?

### How can we reproduce it?

1. Setup provider and add appropriate ProviderConfig
2. Apply the following manifest:

```yaml
apiVersion: projects.gitlab.crossplane.io/v1alpha1
kind: Project
metadata:
  name: test-project
spec:
  deletionPolicy: Delete
  forProvider:
    approvalsBeforeMerge: 1
    defaultBranch: main
    name: Test Project
  managementPolicies:
  - '*'
  providerConfigRef:
    name: provider-gitlab-config
```

Error message:

```
Error from server (BadRequest): error when creating "STDIN": Project in version "v1alpha1" cannot be handled as a Project: strict decoding error: unknown field "spec.forProvider.approvalsBeforeMerge"
```

### What environment did it happen in?
Crossplane version:  v1.19.0
Crossplane Provider GitLab version: v0.11.0
