### ISSUE TITLE
Referenced groups in sharedWithGroups field are not resolved

### ISSUE THREAD

**Issue by asperan** [crossplane-contrib/provider-gitlab#208]
### What happened?

`Group`'s `sharedWithGroups` with `groupIdRef` or `groupIdSelector` seem not to be considered by the provider (which does not print any log, even with debug log level), while using `groupId` works.

This is the cluster status in k9s:
![Image](https://github.com/user-attachments/assets/e009b67a-172b-40b5-b1c4-5c0d06b4d80e)

Thus, sharing a group with another group managed by the provider is not possible.

The same group without `sharedWithGroups` or using directly the `groupId` is created correctly, thus my guess is that there is a bug in the reference resolver.

![Image](https://github.com/user-attachments/assets/234fa2b8-d204-4e81-a5bc-22f669e492bb)

This state is reflected in Gitlab, as the group is not created.

### How can we reproduce it?

Bugged artifact:
```yaml
apiVersion: groups.gitlab.crossplane.io/v1alpha1
kind: Group
metadata:
  name: customer-foo
spec:
  deletionPolicy: Delete
  forProvider:
    name: foo
    # The parentId below exists
    parentId: 985
    path: foo
    sharedWithGroups:
    - groupAccessLevel: 40
      groupIdRef:
        name: team-bar
providerConfigRef:
    name: gitlab-provider-config
```

The same CR, with `groupId` rather than `groupRefId`:
```yaml
apiVersion: groups.gitlab.crossplane.io/v1alpha1
kind: Group
metadata:
  name: customer-foo
spec:
  deletionPolicy: Delete
  forProvider:
    name: foo
    parentId: 985
    path: foo
    sharedWithGroups:
    - groupAccessLevel: 40
      # The groupId below is the ID of the groupRef in the bugged manifest
      groupId: 994
  providerConfigRef:
    name: gitlab-provider-config
```

### What environment did it happen in?
Crossplane version: 1.20.0
Crossplane Provider GitLab version: v0.11.0
Cluster: Kind v1.33.1
