### ISSUE TITLE
unable to create a top-level group at gitlab.com

### ISSUE THREAD

**Issue by janwillies** [crossplane-contrib/provider-gitlab#22]
### What happened?
It's impossible to create a [global group](https://docs.gitlab.com/ee/api/groups.html#new-group) in gitlab (at least with the free acount on gitlab.com), the only group which works is a [Subgroup](https://docs.gitlab.com/ee/api/groups.html#new-subgroup) (e.g. setting the `parentId` to the id of an already existing group)

### How can we reproduce it?
Create a group without setting `parentId`, or setting it to 0.
```yaml
apiVersion: groups.gitlab.crossplane.io/v1alpha1
kind: Group
metadata:
  name: example-group
spec:
  forProvider:
    # parentId: 0
    path: test-asdf08
    description: "example description"
  providerConfigRef:
    name: gitlab-provider
  # a reference to a Kubernetes secret to which the controller will write the runnersToken
  writeConnectionSecretToRef:
    name: gitlab-group-example-group
    namespace: crossplane-system
```

FWIW, it doesn't work with `curl` either:
```bash
curl -X POST --header "PRIVATE-TOKEN: $TOKEN" --header "Content-Type: application/json"  --data '{"path":"foab2348945845","name":"asdafasdfas","parent_id":0}' https://gitlab.com/api/v4/groups 
{"message":"404 Group Not Found"}

curl -X POST --header "PRIVATE-TOKEN: $TOKEN" --header "Content-Type: application/json"  --data '{"path":"foab2348945845","name":"asdafasdfas"}' https://gitlab.com/api/v4/groups
{"message":"403 Forbidden"}
```

### What environment did it happen in?
Crossplane version: v1.1.1
Crossplane Provider GitLab version: 5029e6b
