### ISSUE TITLE
add referencers for groups

### ISSUE THREAD

**Issue by janwillies** [crossplane-contrib/provider-gitlab#23]
### What problem are you facing?
When creating a `project` or a `group` which references another group as its `parentId` I want to be able to use kubernetes references instead of hardcoded IDs.

### How could Crossplane help solve your problem?
the `group` resource should implement kubernetes references, like for the `project` resource: https://github.com/crossplane-contrib/provider-gitlab/blob/master/apis/projects/v1alpha1/referencers.go. There should be new types for `group`:
```yaml
parentId: 1234
parentIdRef:
  name: parent-group
parentIdSelector:
  labelName: labelValue
```
similar for `projects`:
```yaml
namespaceId: 1234
namespaceIdRef:
  name: parent-group
namespaceIdSelector:
  labelName: labelValue
```
