### ISSUE TITLE
Implement Project / Group Variables

### ISSUE THREAD

**Issue by benagricola** [crossplane-contrib/provider-gitlab#46]
### What problem are you facing?
We need to be able to set project (and potentially group) level CI/CD variables to control deployments of template-imported projects.

### How could Crossplane help solve your problem?
Implement a new resource type, `Variable` or similar which uses the [Variables API](https://docs.gitlab.com/ee/api/project_level_variables.html) to CRUD variables on a project or group.

A Hi-fi implementation would suggest to use two types, e.g. `Variable` under each API group, which resolves the appropriate project or group, and potentially resolve a secret, or simply take a plaintext value to set the variable.

I was thinking of an initial API like the following (replace `project` with `group` for the second type):

```yaml
apiVersion: projects.gitlab.crossplane.io/v1alpha1
kind: Variable
metadata:
  name: deploy-arn
spec:
  forProvider:
    projectIdRef:
      name: my-project
    # projectId: 1234
    # projectIdSelector:
    #   matchLabels:
    #     project-type: blah
    type: env_var # (default) or file
    protected: true
    masked: false
    environmentScope: "dev/*"
    key: AWS_ROLE_ARN
    value: arn:aws:iam::999999999:role/my-deploy-role
```

Happy to implement this if the API design looks good.
