### ISSUE TITLE
[project]: create project without setting external-name annotation

### ISSUE THREAD

**Issue by janwillies** [crossplane-contrib/provider-gitlab#7]
### What happened?
Creating a `project` without the `crossplane.io/external-name` annotation fails because the `name` is blank and the gitlab api refuses this:
```json
{
   "object":{
      "kind":"Project",
      "name":"example-project",
      "uid":"96170c21-04cc-49e4-b533-1edff54b5aed",
      "apiVersion":"projects.gitlab.crossplane.io/v1alpha1",
      "resourceVersion":"5730"
   },
   "reason":"CannotCreateExternalResource",
   "message":"cannot create Gitlab project: POST https://gitlab.com/api/v4/projects: 400 {message: {limit_reached: []}, {name: [can't be blank, can contain only letters, digits, emojis, '_', '.', dash, space. It must start with letter, digit, emoji or '_'.]}, {path: [can't be blank, can contain only letters, digits, '_', '-' and '.'. Cannot start with '-', end in '.git' or end in '.atom', is too short (minimum is 1 character)]}}"
}
```

`provider-gitlab` should use `metadata.name` as the name.

### How can we reproduce it?
create a project without the `crossplane.io/external-name` annotation:
```yaml
apiVersion: projects.gitlab.crossplane.io/v1alpha1
kind: Project
metadata:
  name: example-project
  # annotations:
  #   crossplane.io/external-name: example-project
spec:
  forProvider:
    namespaceId: 12345678
    description: "an example project"
  providerConfigRef:
    name: gitlab-provider
  # a reference to a Kubernetes secret to which the controller will write the runnersToken
  writeConnectionSecretToRef:
    name: gitlab-project-example-project
    namespace: crossplane-system
```

### What environment did it happen in?
provider-gitlab version: 9c0dd48afddab972940e7bbea29b52a5da6d2232
